language: python

python:
  - "3.6"

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database authors_dojo;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - py.test

after_success:
  - coveralls
