# Generated by Django 2.1 on 2019-05-03 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_likes', '0003_articlelike_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlelike',
            old_name='author',
            new_name='liked_by',
        ),
    ]
