# Generated by Django 2.1 on 2019-05-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_likes', '0004_auto_20190503_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlelike',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
