# Generated by Django 2.1 on 2019-04-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('description', models.TextField()),
                ('publish_status', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('delete_status', models.BooleanField(default=False)),
            ],
        ),
    ]
