# Generated by Django 2.1 on 2019-05-07 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritearticle',
            name='favorited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='article',
            name='tagList',
            field=models.ManyToManyField(related_name='articles', to='article_tag.ArticleTag'),
        ),
        migrations.AlterUniqueTogether(
            name='readingstats',
            unique_together={('article', 'reads', 'views')},
        ),
    ]
