# Generated by Django 2.1 on 2019-05-13 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20190508_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingstats',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='readingstats',
            name='reads',
        ),
        migrations.RemoveField(
            model_name='readingstats',
            name='views',
        ),
        migrations.AlterUniqueTogether(
            name='readingstats',
            unique_together={('article', 'user')},
        ),
    ]
