# Generated by Django 2.1 on 2019-05-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190507_0930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readingstats',
            unique_together=set(),
        ),
    ]
