# Generated by Django 2.1 on 2019-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='end_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='highlighted_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='start_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
