# Generated by Django 2.1 on 2019-05-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_follows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorfollowing',
            name='follower',
            field=models.CharField(max_length=255),
        ),
    ]
